//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.16 at 02:44:05 PM CEST 
//


package charlie.zha.noFactory;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="billing-address" type="{http://www.example.org/customer}address-type"/&gt;
 *         &lt;element name="shipping-address" type="{http://www.example.org/customer}address-type"/&gt;
 *         &lt;element name="nillableString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "billingAddress",
    "shippingAddress",
    "nillableString"
})
@XmlRootElement(name = "customer")
@XmlRegistry
public class Customer {

    public static final QName NILLABLE_STRING = new QName("nillableString");
    @XmlElement(name = "billing-address", required = true)
    protected AddressType billingAddress;
    @XmlElement(name = "shipping-address", required = true)
    protected AddressType shippingAddress;
    @XmlElementRef(name = "nillableString", type = JAXBElement.class, required = false)
    protected  JAXBElement<String> nillableString;


    @XmlElementDecl(name = "nillableString",scope = Customer.class)
    public JAXBElement<String> createNillableString(String value) {
        return new JAXBElement<>(NILLABLE_STRING,String.class, value);
    }

    /**
     * Gets the value of the billingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *
     */
    public AddressType getBillingAddress() {
        return billingAddress;
    }

    /**
     * Sets the value of the billingAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *
     */
    public void setBillingAddress(AddressType value) {
        this.billingAddress = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     *
     * @return
     *     possible object is
     *     {@link AddressType }
     *
     */
    public AddressType getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *
     */
    public void setShippingAddress(AddressType value) {
        this.shippingAddress = value;
    }

    /**
     * Gets the value of the nillableString property.
     *
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    public  JAXBElement<String> getNillableString() {
        return nillableString;
    }

    /**
     * Sets the value of the nillableString property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNillableString(String value) {
        this.nillableString = new JAXBElement<>(NILLABLE_STRING,String.class,value);
    }

}
